# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Analytics',
  source 'https://github.com/CocoaPods/Specs.git'
  target 'YOUR_APPLICATION_TARGET_NAME_HERE' do
    pod 'GoogleMaps', '5.0.0'
  end

  # Pods for Runner

end
